<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Language;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'code' => 'JP',
                'three_code' => 'JPN',
                'name' => '日本',
                'name_en' => 'Japan',
                'country_code' => 81,
                'language_code' => 'ja',
                'stages' => 30,
            ],
            [
                'code' => 'IS',
                'three_code' => 'ISL',
                'name' => 'アイスランド',
                'name_en' => 'Iceland',
                'country_code' => 354,
                'language_code' => 'is',
                'stages' => 10,
            ],
            [
                'code' => 'IE',
                'three_code' => 'IRL',
                'name' => 'アイルランド',
                'name_en' => 'Ireland',
                'country_code' => 353,
                'language_code' => 'en',
                'stages' => 10,
            ],
            [
                'code' => 'AZ',
                'three_code' => 'AZE',
                'name' => 'アゼルバイジャン',
                'name_en' => 'Azerbaijan',
                'country_code' => 994,
                'language_code' => 'az',
                'stages' => 10,
            ],
            [
                'code' => 'AF',
                'three_code' => 'AFG',
                'name' => 'アフガニスタン',
                'name_en' => 'Afghanistan',
                'country_code' => 93,
                'language_code' => 'fa',
                'stages' => 10,
            ],
            [
                'code' => 'US',
                'three_code' => 'USA',
                'name' => 'アメリカ合衆国',
                'name_en' => 'United States of America',
                'country_code' => 1,
                'language_code' => 'en',
                'stages' => 20,
            ],
            [
                'code' => 'AE',
                'three_code' => 'ARE',
                'name' => 'アラブ首長国連邦',
                'name_en' => 'United Arab Emirates',
                'country_code' => 971,
                'language_code' => 'ar',
                'stages' => 15,
            ],
            [
                'code' => 'DZ',
                'three_code' => 'DZA',
                'name' => 'アルジェリア',
                'name_en' => 'Algeria',
                'country_code' => 213,
                'language_code' => 'ar',
                'stages' => 10,
            ],
            [
                'code' => 'AR',
                'three_code' => 'ARG',
                'name' => 'アルゼンチン',
                'name_en' => 'Argentina',
                'country_code' => 54,
                'language_code' => 'es',
                'stages' => 10,
            ],
            [
                'code' => 'AL',
                'three_code' => 'ALB',
                'name' => 'アルバニア',
                'name_en' => 'Albania',
                'country_code' => 355,
                'language_code' => 'sq',
                'stages' => 10,
            ],
            [
                'code' => 'AM',
                'three_code' => 'ARM',
                'name' => 'アルメニア',
                'name_en' => 'Armenia',
                'country_code' => 374,
                'language_code' => 'hy',
                'stages' => 10,
            ],
            [
                'code' => 'AO',
                'three_code' => 'AGO',
                'name' => 'アンゴラ',
                'name_en' => 'Angola',
                'country_code' => 244,
                'language_code' => 'pt',
                'stages' => 10,
            ],
            [
                'code' => 'YE',
                'three_code' => 'YEM',
                'name' => 'イエメン',
                'name_en' => 'Yemen',
                'country_code' => 967,
                'language_code' => 'ar',
                'stages' => 10,
            ],
            [
                'code' => 'GB',
                'three_code' => 'GBR',
                'name' => 'イギリス',
                'name_en' => 'United Kingdom',
                'country_code' => 44,
                'language_code' => 'en',
                'stages' => 10,
            ],
            [
                'code' => 'IL',
                'three_code' => 'ISR',
                'name' => 'イスラエル',
                'name_en' => 'Israel',
                'country_code' => 972,
                'language_code' => 'he',
                'stages' => 10,
            ],
            [
                'code' => 'IT',
                'three_code' => 'ITA',
                'name' => 'イタリア',
                'name_en' => 'Italy',
                'country_code' => 39,
                'language_code' => 'it',
                'stages' => 10,
            ],
            [
                'code' => 'IQ',
                'three_code' => 'IRQ',
                'name' => 'イラク',
                'name_en' => 'Iraq',
                'country_code' => 964,
                'language_code' => 'ar',
                'stages' => 10,
            ],
            [
                'code' => 'IR',
                'three_code' => 'IRN',
                'name' => 'イラン・イスラム共和国',
                'name_en' => 'Iran',
                'country_code' => 98,
                'language_code' => 'fa',
                'stages' => 10,
            ],
            [
                'code' => 'IN',
                'three_code' => 'IND',
                'name' => 'インド',
                'name_en' => 'India',
                'country_code' => 91,
                'language_code' => 'hi',
                'stages' => 10,
            ],
            [
                'code' => 'ID',
                'three_code' => 'IDN',
                'name' => 'インドネシア',
                'name_en' => 'Indonesia',
                'country_code' => 62,
                'language_code' => 'id',
                'stages' => 10,
            ],
            [
                'code' => 'UG',
                'three_code' => 'UGA',
                'name' => 'ウガンダ',
                'name_en' => 'Uganda',
                'country_code' => 256,
                'language_code' => 'en',
                'stages' => 10,
            ],
            [
                'code' => 'UA',
                'three_code' => 'UKR',
                'name' => 'ウクライナ',
                'name_en' => 'Ukraine',
                'country_code' => 380,
                'language_code' => 'uk',
                'stages' => 10,
            ],
            [
                'code' => 'UZ',
                'three_code' => 'UZB',
                'name' => 'ウズベキスタン',
                'name_en' => 'Uzbekistan',
                'country_code' => 998,
                'language_code' => 'uz',
                'stages' => 10,
            ],
            [
                'code' => 'UY',
                'three_code' => 'URY',
                'name' => 'ウルグアイ',
                'name_en' => 'Uruguay',
                'country_code' => 598,
                'language_code' => 'es',
                'stages' => 10,
            ],
            [
                'code' => 'EC',
                'three_code' => 'ECU',
                'name' => 'エクアドル',
                'name_en' => 'Ecuador',
                'country_code' => 593,
                'language_code' => 'es',
                'stages' => 10,
            ],
            [
                'code' => 'EG',
                'three_code' => 'EGY',
                'name' => 'エジプト',
                'name_en' => 'Egypt',
                'country_code' => 20,
                'language_code' => 'ar',
                'stages' => 10,
            ],
            [
                'code' => 'EE',
                'three_code' => 'EST',
                'name' => 'エストニア',
                'name_en' => 'Estonia',
                'country_code' => 372,
                'language_code' => 'et',
                'stages' => 10,
            ],
            [
                'code' => 'ET',
                'three_code' => 'ETH',
                'name' => 'エチオピア',
                'name_en' => 'Ethiopia',
                'country_code' => 251,
                'language_code' => 'am',
                'stages' => 10,
            ],
            [
                'code' => 'SV',
                'three_code' => 'SLV',
                'name' => 'エルサルバドル',
                'name_en' => 'El Salvador',
                'country_code' => 503,
                'language_code' => 'es',
                'stages' => 10,
            ],
            [
                'code' => 'OM',
                'three_code' => 'OMN',
                'name' => 'オマーン',
                'name_en' => 'Oman',
                'country_code' => 968,
                'language_code' => 'ar',
                'stages' => 10,
            ],
            [
                'code' => 'AU',
                'three_code' => 'AUS',
                'name' => 'オーストラリア',
                'name_en' => 'Australia',
                'country_code' => 61,
                'language_code' => 'en',
                'stages' => 10,
            ],
            [
                'code' => 'AT',
                'three_code' => 'AUT',
                'name' => 'オーストリア',
                'name_en' => 'Austria',
                'country_code' => 43,
                'language_code' => 'de',
                'stages' => 10,
            ],
            [
                'code' => 'NL',
                'three_code' => 'NLD',
                'name' => 'オランダ',
                'name_en' => 'Netherlands',
                'country_code' => 31,
                'language_code' => 'nl',
                'stages' => 10,
            ],
            [
                'code' => 'KR',
                'three_code' => 'KOR',
                'name' => '韓国',
                'name_en' => 'South Korea',
                'country_code' => 82,
                'language_code' => 'ko',
                'stages' => 10,
            ],
            [
                'code' => 'CA',
                'three_code' => 'CAN',
                'name' => 'カナダ',
                'name_en' => 'Canada',
                'country_code' => 1,
                'language_code' => 'en',
                'stages' => 10,
            ],
            [
                'code' => 'GR',
                'three_code' => 'GRC',
                'name' => 'ギリシャ',
                'name_en' => 'Greece',
                'country_code' => 30,
                'language_code' => 'el',
                'stages' => 10,
            ],
            [
                'code' => 'CL',
                'three_code' => 'CHL',
                'name' => 'チリ',
                'name_en' => 'Chile',
                'country_code' => 56,
                'language_code' => 'es',
                'stages' => 10,
            ],
            [
                'code' => 'CN',
                'three_code' => 'CHN',
                'name' => '中国',
                'name_en' => 'China',
                'country_code' => 86,
                'language_code' => 'zh',
                'stages' => 10,
            ],
            [
                'code' => 'CH',
                'three_code' => 'CHE',
                'name' => 'スイス',
                'name_en' => 'Switzerland',
                'country_code' => 41,
                'language_code' => 'de',
                'stages' => 10,
            ],
            [
                'code' => 'SE',
                'three_code' => 'SWE',
                'name' => 'スウェーデン',
                'name_en' => 'Sweden',
                'country_code' => 46,
                'language_code' => 'sv',
                'stages' => 10,
            ],
            [
                'code' => 'SK',
                'three_code' => 'SVK',
                'name' => 'スロバキア',
                'name_en' => 'Slovakia',
                'country_code' => 421,
                'language_code' => 'sk',
                'stages' => 10,
            ],
            [
                'code' => 'FR',
                'three_code' => 'FRA',
                'name' => 'フランス',
                'name_en' => 'France',
                'country_code' => 33,
                'language_code' => 'fr',
                'stages' => 20,
            ],
            [
                'code' => 'ES',
                'three_code' => 'ESP',
                'name' => 'スペイン',
                'name_en' => 'Spain',
                'country_code' => 34,
                'language_code' => 'es',
                'stages' => 20,
            ],
            [
                'code' => 'PT',
                'three_code' => 'PRT',
                'name' => 'ポルトガル',
                'name_en' => 'Portugal',
                'country_code' => 351,
                'language_code' => 'pt',
                'stages' => 10,
            ],
            [
                'code' => 'TH',
                'three_code' => 'THA',
                'name' => 'タイ',
                'name_en' => 'Thailand',
                'country_code' => 66,
                'language_code' => 'th',
                'stages' => 10,
            ],
        ];

        foreach ($countries as $index => $country) {
            $language = Language::query()->where('code', $country['language_code'])->first();

            $record = Country::query()->firstOrCreate(
                ['code' => $country['code']],
                ['name' => $country['name'], 'stages' => $country['stages'], 'order' => $index]
            );

            if ($language) {
                $record->languages()->syncWithoutDetaching([
                    $language->id => ['is_primary' => true],
                ]);
            }
        }
    }
}
