import { CATEGORY_LABELS, type ItemCategory } from "./categories";

/** 町のアイテムの絵のキー。config/world.php の asset_keys と必ず一致させる(art-keys.test.ts で確かめる) */
export const ITEM_ART_KEYS = [
  "bench",
  "flowerbed",
  "chochin",
  "tree",
  "sakura",
  "vending",
  "bicycle",
  "stall",
  "stone_lantern",
  "bamboo",
  "fountain",
  "palm",
  "parasol",
  "pagoda",
  "castle",
  "tower",
  "boat_small",
  "boat_large",
  // 段階2・3(docs/design/2026-09-28-town-items-design.md 5-2)
  "tulip",
  "rock",
  "sunflower",
  "bush",
  "momiji",
  "pine",
  "flower_pots",
  "well",
  "street_lamp",
  "mailbox",
  "cottage",
  "red_house",
  "bakery",
  "japanese_house",
  "cafe",
  "lighthouse",
  // 特別の名所(docs/design/2026-09-28-town-items-design.md 5-4)
  "kinkakuji",
  "sungnyemun",
  "arc_de_triomphe",
  "big_ben",
  // Spra-worldの確定画像(docs/design/2026-10-05-world-items-stage1-design.md)
  "young_tree",
  "pathside_flowers",
  "pathside_stone",
  "stream",
  "vegetable_bed",
  "broadleaf_tree",
  "spring",
  "large_tree",
  "leaf_lamp",
  "wooden_bridge",
  "woodland_torii",
  "seed_storehouse",
  "resident_cottage",
  "leaf_cottage",
  "blue_flower_cottage",
  "forest_flower_house",
  "greengrocer",
  "fish_shop",
  "meat_shop",
  "produce_shop",
  "chief_hall",
  "stone_tower_hall",
  "windmill_garden",
  "spru_mall",
  "saku_mall",
] as const;

export type ItemArtKey = (typeof ITEM_ART_KEYS)[number];

/** おみやげの絵のキー。config/travel.php のおみやげのキーと必ず一致させる。ショップでは売らないので asset_keys には入れない */
export const SOUVENIR_ART_KEYS = [
  "komodo",
  "borobudur",
  "dol_hareubang",
  "bulguksa",
  "bison",
  "liberty",
  "phone_box",
  "stonehenge",
  "eiffel",
  "mont_saint_michel",
] as const;

export type SouvenirArtKey = (typeof SOUVENIR_ART_KEYS)[number];

export type ArtKey = ItemArtKey | SouvenirArtKey;

/** 管理画面(ショップ編集)の絵の選択肢に出す名前。カテゴリと大きさは artOptionLabel で添える */
export const ITEM_ART_LABELS: Record<ItemArtKey, string> = {
  bench: "ベンチ",
  flowerbed: "花だん",
  chochin: "ちょうちん",
  tree: "木",
  sakura: "桜の木",
  vending: "自動販売機",
  bicycle: "自転車",
  stall: "屋台",
  stone_lantern: "石灯籠",
  bamboo: "竹",
  fountain: "噴水",
  palm: "ヤシの木",
  parasol: "ビーチパラソル",
  pagoda: "五重塔",
  castle: "お城",
  tower: "タワー",
  boat_small: "小さな船",
  boat_large: "大きな船",
  tulip: "チューリップ",
  rock: "岩と草",
  sunflower: "ひまわり",
  bush: "まるい植え込み",
  momiji: "もみじ",
  pine: "松",
  flower_pots: "植木鉢",
  well: "井戸",
  street_lamp: "街灯",
  mailbox: "ポスト",
  cottage: "小さな家",
  red_house: "赤い屋根の家",
  bakery: "パン屋",
  japanese_house: "和風の家",
  cafe: "カフェ",
  lighthouse: "灯台",
  kinkakuji: "金閣寺",
  sungnyemun: "南大門",
  arc_de_triomphe: "凱旋門",
  big_ben: "ビッグ・ベン",
  // Spra-worldの確定画像(docs/design/2026-10-05-world-items-stage1-design.md)
  young_tree: "若い木",
  pathside_flowers: "道ばたの花",
  pathside_stone: "道ばたの石",
  stream: "小川",
  vegetable_bed: "菜園",
  broadleaf_tree: "広葉樹",
  spring: "わき水の泉",
  large_tree: "大きな木",
  leaf_lamp: "はっぱの街灯",
  wooden_bridge: "木の橋",
  woodland_torii: "鳥居",
  seed_storehouse: "種の倉庫",
  resident_cottage: "村人の家",
  leaf_cottage: "葉の屋根の家",
  blue_flower_cottage: "青い花の家",
  forest_flower_house: "森の花の家",
  greengrocer: "八百屋",
  fish_shop: "魚屋",
  meat_shop: "肉屋",
  produce_shop: "野菜のお店",
  chief_hall: "村長の家",
  stone_tower_hall: "石の塔の家",
  windmill_garden: "風車と水の庭",
  spru_mall: "スプルモール",
  saku_mall: "サクモール",
};

/** 絵のカテゴリ(設計書 2026-09-28-town-items 3-2)。config/world.php の asset_categories と必ず一致させる */
export const ITEM_ART_CATEGORIES: Record<ItemArtKey, ItemCategory> = {
  bench: "decor",
  flowerbed: "nature",
  chochin: "decor",
  tree: "nature",
  sakura: "nature",
  vending: "decor",
  bicycle: "vehicle",
  stall: "house",
  stone_lantern: "decor",
  bamboo: "nature",
  fountain: "decor",
  palm: "nature",
  parasol: "decor",
  pagoda: "landmark",
  castle: "landmark",
  tower: "landmark",
  boat_small: "vehicle",
  boat_large: "vehicle",
  tulip: "nature",
  rock: "nature",
  sunflower: "nature",
  bush: "nature",
  momiji: "nature",
  pine: "nature",
  flower_pots: "decor",
  well: "decor",
  street_lamp: "decor",
  mailbox: "decor",
  cottage: "house",
  red_house: "house",
  bakery: "house",
  japanese_house: "house",
  cafe: "house",
  lighthouse: "landmark",
  kinkakuji: "landmark",
  sungnyemun: "landmark",
  arc_de_triomphe: "landmark",
  big_ben: "landmark",
  // Spra-worldの確定画像(docs/design/2026-10-05-world-items-stage1-design.md)
  young_tree: "nature",
  pathside_flowers: "nature",
  pathside_stone: "nature",
  stream: "nature",
  vegetable_bed: "nature",
  broadleaf_tree: "nature",
  spring: "nature",
  large_tree: "nature",
  leaf_lamp: "decor",
  wooden_bridge: "decor",
  woodland_torii: "landmark",
  seed_storehouse: "house",
  resident_cottage: "house",
  leaf_cottage: "house",
  blue_flower_cottage: "house",
  forest_flower_house: "house",
  greengrocer: "house",
  fish_shop: "house",
  meat_shop: "house",
  produce_shop: "house",
  chief_hall: "landmark",
  stone_tower_hall: "landmark",
  windmill_garden: "landmark",
  spru_mall: "landmark",
  saku_mall: "landmark",
};

/** 管理画面の絵の選択肢の名前。カテゴリと、2×2なら大きさを添える(例: 「五重塔（名所・2×2）」) */
export function artOptionLabel(key: ItemArtKey): string {
  const footprint = assetFootprint(key);
  const size = footprint > 1 ? `・${footprint}×${footprint}` : "";
  return `${ITEM_ART_LABELS[key]}（${CATEGORY_LABELS[ITEM_ART_CATEGORIES[key]]}${size}）`;
}

/** 2×2・3×3マスの絵の大きさ(設計書 2026-09-27-wave-e 3-4、2026-10-07-town-sizes 4-1)。書いていない絵は1×1。config/world.php の asset_footprints と必ず一致させる */
export const ASSET_FOOTPRINTS: Readonly<Partial<Record<ArtKey, number>>> = {
  fountain: 2,
  pagoda: 3,
  castle: 3,
  tower: 2,
  boat_large: 2,
  borobudur: 2,
  bulguksa: 2,
  liberty: 2,
  stonehenge: 2,
  mont_saint_michel: 2,
  bakery: 2,
  japanese_house: 2,
  cafe: 2,
  lighthouse: 2,
  kinkakuji: 2,
  sungnyemun: 2,
  arc_de_triomphe: 2,
  big_ben: 2,
  large_tree: 2,
  greengrocer: 2,
  fish_shop: 2,
  meat_shop: 2,
  produce_shop: 2,
  chief_hall: 3,
  stone_tower_hall: 2,
  windmill_garden: 3,
  spru_mall: 3,
  saku_mall: 3,
};

/** 絵の大きさ(N×NのN)。1(小)・2(中)・3(大)。絵がなければ1 */
export function assetFootprint(key: string | null): number {
  return key === null ? 1 : ((ASSET_FOOTPRINTS as Record<string, number | undefined>)[key] ?? 1);
}

export function isBigAsset(key: string | null): boolean {
  return assetFootprint(key) > 1;
}
